Fix deployment
MapColonies/automation-locust-framework pull request #27
Opened 2023-06-06 11:19 UTC by shyeavr

finish percent calculation redesign and elevation test

2023-06-06 13:52 UTC, dannysigalovich commented on tests/pycsw/test_data/queries.py
Why you removed new line marker?

2023-06-06 14:08 UTC, dannysigalovich requested changes
Look at the comments i have added. and i forgot to add comment of the variables in camel case. 
python should use underscore. myDir => my_directory / my_dir

2023-06-06 14:08 UTC, dannysigalovich commented on tests/proactive/csw_wmts-proactive.py
> +sys.path.insert(0, '../..')
setup.py won't work ?

2023-06-07 06:33 UTC, dannysigalovich requested changes
Approve the changes i requested

2023-06-07 07:43 UTC, shyeavr commented on tests/proactive/csw_wmts-proactive.py
> +sys.path.insert(0, '../..')
what?

2023-06-07 09:00 UTC, dannysigalovich approved these changes

2023-06-07 09:00 UTC, merged