3d test new
MapColonies/automation-locust-framework pull request #35
Opened 2023-07-27 10:42 UTC by shyeavr

Add Yoad test, generate points by polygon function , retype env function

2023-07-27 12:54 UTC, dannysigalovich requested changes
@shyeavr please fix the code :) double check me !

2023-07-27 12:54 UTC, dannysigalovich commented on common/utils/data_generator/data_utils.py
> +
# Define constants
PRODUCT_TYPES = ["DSM", "DTM", "MIXED"]

2023-07-27 12:54 UTC, dannysigalovich commented on common/utils/data_generator/data_utils.py
> +def polygon_random_points(polygon: list, num_points: int) -> list:
```
def polygon_random_points(polygon: List[Tuple[float, float]], num_points: int) -> List[Tuple[float, float]]:

double check me
```

2023-07-27 12:54 UTC, dannysigalovich commented on common/utils/data_generator/data_utils.py
> +def generate_points_request(
points_amount: int, polygon: List[Tuple[float, float]], exclude_fields: bool, product_type: str = "MIXED"

Make it harder - double check me

2023-07-27 12:54 UTC, dannysigalovich commented on common/utils/data_generator/data_utils.py
> +    points_list = []
points_list = [{"longitude": lon, "latitude": lat} for lon, lat in points_data]

2023-07-27 12:54 UTC, dannysigalovich commented on common/utils/data_generator/data_utils.py
> +    points_list = []
it replace the for

2023-07-27 12:54 UTC, dannysigalovich commented on common/utils/data_generator/data_utils.py
> +def generate_points_request(
```
def generate_points_request(
    points_amount: int, polygon: List[Tuple[float, float]], exclude_fields: bool, product_type: str = "MIXED"
) 
```

2023-07-27 12:54 UTC, dannysigalovich commented on common/utils/data_generator/data_utils.py
> +    if payload_flag:
```
if exclude_fields:
        request_body = {
            "positions": points_list,
            "productType": product_type,
            "excludeFields": []
        }
    else:
        request_body = {
            "positions": points_list,
            "productType": product_type,
            "excludeFields": ["productType", "updateDate", "resolutionMeter"]
        }

    return json.dumps(request_body)
```

2023-07-27 12:54 UTC, dannysigalovich commented on tests/elevation_service/one_point_per_user.py
> +        graph_title=None,
The graph_title parameter of create_custom_graph is set to None. If there is a specifisc title for the graph make it clarity!

2023-07-27 12:54 UTC, dannysigalovich commented on tests/elevation_service/one_point_per_user.py
>  def on_locust_stop(environment, **kwargs):
the code lacks comments and docstrings

2023-07-27 12:54 UTC, dannysigalovich commented on tests/elevation_service/one_point_per_user.py
> +        percent_range = (value / total_requests) * 100
Magic number? what is 100

2023-07-27 12:54 UTC, dannysigalovich commented on tests/elevation_service/one_point_per_user.py
>  def response_time_listener(response_time, **kwargs):
General comment : *kwargs is not good practice, better us meaningful names for function param :)

2023-07-27 12:54 UTC, dannysigalovich commented on tests/elevation_service/one_point_per_user.py
> +def reset_data_counters(**kwargs):
General comment : *kwargs is not good practice, better us meaningful names for function param :)

2023-07-27 12:54 UTC, dannysigalovich commented on tests/elevation_service/elevation-integ.py
>      def index(self):
```
def index(self):
    payload_type = self.request_body["request_type"]
    payload = self.request_body["body"]
    headers = self.request_body["header"]
    verify = False 

    if payload_type == "json":
        self.client.post("/", json=payload, headers=headers, verify=verify)
    elif payload_type == "bin":
        self.client.post("/", data=payload, headers=headers, verify=verify)
```

2023-07-27 12:54 UTC, dannysigalovich commented on common/utils/data_generator/data_utils.py
> +
not sure

2023-07-27 13:35 UTC, dannysigalovich approved these changes

2023-08-08 08:27 UTC, closed without merging

2023-08-08 08:27 UTC, shyeavr commented
change all comments